# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editOrderDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OrderEditDialog(object):
    def setupUi(self, OrderEditDialog):
        OrderEditDialog.setObjectName("OrderEditDialog")
        OrderEditDialog.resize(481, 484)
        OrderEditDialog.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhNoTextHandles)
        self.save_push_button = QtWidgets.QPushButton(OrderEditDialog)
        self.save_push_button.setGeometry(QtCore.QRect(180, 390, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_push_button.setFont(font)
        self.save_push_button.setObjectName("save_push_button")
        self.second_name_label = QtWidgets.QLabel(OrderEditDialog)
        self.second_name_label.setGeometry(QtCore.QRect(100, 320, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.second_name_label.setFont(font)
        self.second_name_label.setObjectName("second_name_label")
        self.is_payed_check_box = QtWidgets.QCheckBox(OrderEditDialog)
        self.is_payed_check_box.setGeometry(QtCore.QRect(200, 220, 16, 17))
        self.is_payed_check_box.setText("")
        self.is_payed_check_box.setObjectName("is_payed_check_box")
        self.year_order_spin_box = QtWidgets.QSpinBox(OrderEditDialog)
        self.year_order_spin_box.setGeometry(QtCore.QRect(300, 100, 51, 22))
        self.year_order_spin_box.setMaximum(9999)
        self.year_order_spin_box.setProperty("value", 2018)
        self.year_order_spin_box.setObjectName("year_order_spin_box")
        self.first_name_label = QtWidgets.QLabel(OrderEditDialog)
        self.first_name_label.setGeometry(QtCore.QRect(100, 290, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.first_name_label.setFont(font)
        self.first_name_label.setObjectName("first_name_label")
        self.first_name_edit = QtWidgets.QLineEdit(OrderEditDialog)
        self.first_name_edit.setGeometry(QtCore.QRect(200, 290, 151, 20))
        self.first_name_edit.setReadOnly(True)
        self.first_name_edit.setObjectName("first_name_edit")
        self.date_order_label_2 = QtWidgets.QLabel(OrderEditDialog)
        self.date_order_label_2.setGeometry(QtCore.QRect(140, 20, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.date_order_label_2.setFont(font)
        self.date_order_label_2.setObjectName("date_order_label_2")
        self.date_order_label = QtWidgets.QLabel(OrderEditDialog)
        self.date_order_label.setGeometry(QtCore.QRect(100, 100, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.date_order_label.setFont(font)
        self.date_order_label.setObjectName("date_order_label")
        self.second_name_edit = QtWidgets.QLineEdit(OrderEditDialog)
        self.second_name_edit.setGeometry(QtCore.QRect(200, 320, 151, 20))
        self.second_name_edit.setReadOnly(True)
        self.second_name_edit.setObjectName("second_name_edit")
        self.phone_number_edit = QtWidgets.QLineEdit(OrderEditDialog)
        self.phone_number_edit.setGeometry(QtCore.QRect(200, 350, 151, 20))
        self.phone_number_edit.setReadOnly(True)
        self.phone_number_edit.setObjectName("phone_number_edit")
        self.cost_label = QtWidgets.QLabel(OrderEditDialog)
        self.cost_label.setGeometry(QtCore.QRect(100, 190, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cost_label.setFont(font)
        self.cost_label.setObjectName("cost_label")
        self.id_payd_label = QtWidgets.QLabel(OrderEditDialog)
        self.id_payd_label.setGeometry(QtCore.QRect(100, 220, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.id_payd_label.setFont(font)
        self.id_payd_label.setObjectName("id_payd_label")
        self.day_order_spin_box = QtWidgets.QSpinBox(OrderEditDialog)
        self.day_order_spin_box.setGeometry(QtCore.QRect(200, 100, 42, 22))
        self.day_order_spin_box.setMinimum(1)
        self.day_order_spin_box.setMaximum(31)
        self.day_order_spin_box.setProperty("value", 31)
        self.day_order_spin_box.setObjectName("day_order_spin_box")
        self.phone_label = QtWidgets.QLabel(OrderEditDialog)
        self.phone_label.setGeometry(QtCore.QRect(100, 350, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.phone_label.setFont(font)
        self.phone_label.setObjectName("phone_label")
        self.month_order_spin_box = QtWidgets.QSpinBox(OrderEditDialog)
        self.month_order_spin_box.setGeometry(QtCore.QRect(250, 100, 42, 22))
        self.month_order_spin_box.setMaximum(12)
        self.month_order_spin_box.setSingleStep(1)
        self.month_order_spin_box.setProperty("value", 12)
        self.month_order_spin_box.setObjectName("month_order_spin_box")
        self.cost_edit = QtWidgets.QLineEdit(OrderEditDialog)
        self.cost_edit.setGeometry(QtCore.QRect(200, 190, 151, 20))
        self.cost_edit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhNoTextHandles)
        self.cost_edit.setObjectName("cost_edit")
        self.id_label = QtWidgets.QLabel(OrderEditDialog)
        self.id_label.setGeometry(QtCore.QRect(100, 70, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.id_label.setFont(font)
        self.id_label.setObjectName("id_label")
        self.day_rendition_spin_box = QtWidgets.QSpinBox(OrderEditDialog)
        self.day_rendition_spin_box.setGeometry(QtCore.QRect(200, 130, 42, 22))
        self.day_rendition_spin_box.setMinimum(0)
        self.day_rendition_spin_box.setMaximum(31)
        self.day_rendition_spin_box.setProperty("value", 31)
        self.day_rendition_spin_box.setObjectName("day_rendition_spin_box")
        self.date_rendition_label = QtWidgets.QLabel(OrderEditDialog)
        self.date_rendition_label.setGeometry(QtCore.QRect(100, 130, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.date_rendition_label.setFont(font)
        self.date_rendition_label.setObjectName("date_rendition_label")
        self.month_rendition_spin_box = QtWidgets.QSpinBox(OrderEditDialog)
        self.month_rendition_spin_box.setGeometry(QtCore.QRect(250, 130, 42, 22))
        self.month_rendition_spin_box.setMinimum(0)
        self.month_rendition_spin_box.setMaximum(12)
        self.month_rendition_spin_box.setSingleStep(1)
        self.month_rendition_spin_box.setProperty("value", 12)
        self.month_rendition_spin_box.setObjectName("month_rendition_spin_box")
        self.year_rendition_spin_box = QtWidgets.QSpinBox(OrderEditDialog)
        self.year_rendition_spin_box.setGeometry(QtCore.QRect(300, 130, 51, 22))
        self.year_rendition_spin_box.setMinimum(0)
        self.year_rendition_spin_box.setMaximum(9999)
        self.year_rendition_spin_box.setProperty("value", 2018)
        self.year_rendition_spin_box.setObjectName("year_rendition_spin_box")
        self.status_label = QtWidgets.QLabel(OrderEditDialog)
        self.status_label.setGeometry(QtCore.QRect(100, 160, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.status_label.setFont(font)
        self.status_label.setObjectName("status_label")
        self.status_spin_box = QtWidgets.QSpinBox(OrderEditDialog)
        self.status_spin_box.setGeometry(QtCore.QRect(200, 160, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.status_spin_box.setFont(font)
        self.status_spin_box.setMaximum(1)
        self.status_spin_box.setObjectName("status_spin_box")
        self.year_pay_spin_box = QtWidgets.QSpinBox(OrderEditDialog)
        self.year_pay_spin_box.setGeometry(QtCore.QRect(300, 250, 51, 22))
        self.year_pay_spin_box.setMaximum(9999)
        self.year_pay_spin_box.setProperty("value", 2018)
        self.year_pay_spin_box.setObjectName("year_pay_spin_box")
        self.day_pay_spin_box = QtWidgets.QSpinBox(OrderEditDialog)
        self.day_pay_spin_box.setGeometry(QtCore.QRect(200, 250, 42, 22))
        self.day_pay_spin_box.setMinimum(0)
        self.day_pay_spin_box.setMaximum(31)
        self.day_pay_spin_box.setProperty("value", 31)
        self.day_pay_spin_box.setObjectName("day_pay_spin_box")
        self.date_pay_label = QtWidgets.QLabel(OrderEditDialog)
        self.date_pay_label.setGeometry(QtCore.QRect(100, 250, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.date_pay_label.setFont(font)
        self.date_pay_label.setObjectName("date_pay_label")
        self.month_pay_spin_box = QtWidgets.QSpinBox(OrderEditDialog)
        self.month_pay_spin_box.setGeometry(QtCore.QRect(250, 250, 42, 22))
        self.month_pay_spin_box.setMaximum(12)
        self.month_pay_spin_box.setSingleStep(1)
        self.month_pay_spin_box.setProperty("value", 12)
        self.month_pay_spin_box.setObjectName("month_pay_spin_box")
        self.id_edit = QtWidgets.QLineEdit(OrderEditDialog)
        self.id_edit.setGeometry(QtCore.QRect(200, 70, 151, 20))
        self.id_edit.setReadOnly(True)
        self.id_edit.setObjectName("id_edit")
        self.cancel_push_button = QtWidgets.QPushButton(OrderEditDialog)
        self.cancel_push_button.setGeometry(QtCore.QRect(180, 420, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancel_push_button.setFont(font)
        self.cancel_push_button.setObjectName("cancel_push_button")

        self.retranslateUi(OrderEditDialog)
        QtCore.QMetaObject.connectSlotsByName(OrderEditDialog)

    def retranslateUi(self, OrderEditDialog):
        _translate = QtCore.QCoreApplication.translate
        OrderEditDialog.setWindowTitle(_translate("OrderEditDialog", "Dialog"))
        self.save_push_button.setText(_translate("OrderEditDialog", "Сохранить"))
        self.second_name_label.setText(_translate("OrderEditDialog", "Фамилия"))
        self.first_name_label.setText(_translate("OrderEditDialog", "Имя заказчика"))
        self.date_order_label_2.setText(_translate("OrderEditDialog", "Редактирование заказа"))
        self.date_order_label.setText(_translate("OrderEditDialog", "Дата принятия"))
        self.cost_label.setText(_translate("OrderEditDialog", "Стоимость"))
        self.id_payd_label.setText(_translate("OrderEditDialog", "Оплачен"))
        self.phone_label.setText(_translate("OrderEditDialog", "Телефон"))
        self.id_label.setText(_translate("OrderEditDialog", "Номер"))
        self.date_rendition_label.setText(_translate("OrderEditDialog", "Дата выдачи"))
        self.status_label.setText(_translate("OrderEditDialog", "Статус"))
        self.date_pay_label.setText(_translate("OrderEditDialog", "Дата оплаты"))
        self.cancel_push_button.setText(_translate("OrderEditDialog", "Отменить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OrderEditDialog = QtWidgets.QDialog()
    ui = Ui_OrderEditDialog()
    ui.setupUi(OrderEditDialog)
    OrderEditDialog.show()
    sys.exit(app.exec_())

